---
- name: Uninstall php-fpm and deps
  apt: name=php5-fpm state=absent purge=yes force=yes
  sudo: yes

- name: Install php-fpm and deps 
  apt: name=php5-fpm state=present
  with_items:
    - php5
    - php5-fpm
    - php5-enchant
    - libphp-*
    #- libidn11-dev
    #- php-IDNA_Convert
    #- php-mbstring
    - php5-mysql
    #- php-PHPMailer
    #- php-process
    #- php-simplepie
    #- php-xml


#- name: Install libidn11-dev (replacement for php-IDNA_Convert)
#  command: pecl install idna

#- name: Disable default pool
#  command: mv /etc/php5-fpm.d/www.conf /etc/php5-fpm.d/www.disabled creates=/etc/php5-fpm.d/www.disabled
#  notify: restart php5-fpm
 
#- name: Copy php-fpm configuration
#  template: src=wordpress.conf dest=/etc/php-fpm.d/
#  notify: restart php-fpm
