---
- name: Uninstall php-fpm and deps
  apt: name=php5-fpm state=absent purge=yes force=yes
  sudo: yes

- name: Install php-fpm and deps 
  apt: name=php5-fpm state=present
  with_items:
    - php5
    - php5-fpm
    - php5-enchant
    - libphp-*
    #- libidn11-dev
    #- php-IDNA_Convert
    #- php-mbstring
    - php5-mysql
    #- php-PHPMailer
    #- php-process
    #- php-simplepie
    #- php-xml