---
- name: restart memcached
  service: name=memcached state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

- name: reload php-fpm
  service: name=php5-fpm state=reloaded

- name: restart php-fpm
  service: name=php5-fpm state=restarted